#pragma once
#include "pch.h"
#include "neatlywrappedsteamapi.h"

namespace steam {

  // clang-format off

  const std::map<EResult, std::string> c_steamEResultDescriptionMap =
  {
    { k_EResultNone, "" },
    { k_EResultOK, "Success." },
    { k_EResultFail, "Generic failure." },
    { k_EResultNoConnection, "Your Steam client doesn't have a connection to the back-end." },
    { k_EResultInvalidPassword, "Password/ticket is invalid." },
    { k_EResultLoggedInElsewhere, "The user is logged in elsewhere." },
    { k_EResultInvalidProtocolVer, "Protocol version is incorrect." },
    { k_EResultInvalidParam, "A parameter is incorrect." },
    { k_EResultFileNotFound, "File was not found." },
    { k_EResultBusy, "Called method is busy - action not taken." },
    { k_EResultInvalidState, "Called object was in an invalid state." },
    { k_EResultInvalidName, "The name was invalid." },
    { k_EResultInvalidEmail, "The email was invalid." },
    { k_EResultDuplicateName, "The name is not unique." },
    { k_EResultAccessDenied, "Access is denied." },
    { k_EResultTimeout, "Operation timed out." },
    { k_EResultBanned, "The user is VAC2 banned." },
    { k_EResultAccountNotFound, "Account not found." },
    { k_EResultInvalidSteamID, "The Steam ID was invalid." },
    { k_EResultServiceUnavailable, "The requested service is currently unavailable." },
    { k_EResultNotLoggedOn, "The user is not logged on." },
    { k_EResultPending, "Request is pending, it may be in process or waiting on third party." },
    { k_EResultEncryptionFailure, "Encryption or Decryption failed." },
    { k_EResultInsufficientPrivilege, "Insufficient privilege." },
    { k_EResultLimitExceeded, "Limit exceeded." },
    { k_EResultRevoked, "Access has been revoked (used for revoked guest passes.)" },
    { k_EResultExpired, "License/Guest pass the user is trying to access is expired." },
    { k_EResultAlreadyRedeemed, "Guest pass has already been redeemed by account, cannot be used again." },
    { k_EResultDuplicateRequest, "The request is a duplicate and the action has already occurred in the past, ignored this time." },
    { k_EResultAlreadyOwned, "All the games in this guest pass redemption request are already owned by the user." },
    { k_EResultIPNotFound, "IP address not found." },
    { k_EResultPersistFailed, "Failed to write change to the data store." },
    { k_EResultLockingFailed, "Failed to acquire access lock for this operation." },
    { k_EResultLogonSessionReplaced, "The logon session has been replaced." },
    { k_EResultConnectFailed, "Failed to connect." },
    { k_EResultHandshakeFailed, "The authentication handshake has failed." },
    { k_EResultIOFailure, "There has been a generic IO failure." },
    { k_EResultRemoteDisconnect, "The remote server has disconnected." },
    { k_EResultShoppingCartNotFound, "Failed to find the shopping cart requested." },
    { k_EResultBlocked, "A user blocked the action." },
    { k_EResultIgnored, "The target is ignoring sender." },
    { k_EResultNoMatch, "Nothing matching the request found." },
    { k_EResultAccountDisabled, "The account is disabled." },
    { k_EResultServiceReadOnly, "This service is not accepting content changes right now." },
    { k_EResultAccountNotFeatured, "Account doesn't have value, so this feature isn't available." },
    { k_EResultAdministratorOK, "Allowed to take this action, but only because requester is admin." },
    { k_EResultContentVersion, "A Version mismatch in content transmitted within the Steam protocol." },
    { k_EResultTryAnotherCM, "The current CM can't service the user making a request, user should try another." },
    { k_EResultPasswordRequiredToKickSession,"You are already logged in elsewhere, this cached credential login has failed." },
    { k_EResultAlreadyLoggedInElsewhere, "The user is logged in elsewhere. (Use k_EResultLoggedInElsewhere instead)" },
    { k_EResultSuspended, "Long running operation has suspended/paused. (eg. content download.)" },
    { k_EResultCancelled, "Operation has been canceled, typically by user. (eg. a content download.)" },
    { k_EResultDataCorruption, "Operation canceled because data is ill formed or unrecoverable." },
    { k_EResultDiskFull, "Operation canceled - not enough disk space." },
    { k_EResultRemoteCallFailed, "The remote or IPC call has failed." },
    { k_EResultPasswordUnset, "Password could not be verified as it's unset server side." },
    { k_EResultExternalAccountUnlinked, "External account (PSN, Facebook...) is not linked to a Steam account." },
    { k_EResultPSNTicketInvalid, "PSN ticket was invalid." },
    { k_EResultExternalAccountAlreadyLinked, "External account (PSN, Facebook...) is already linked to some other account, must explicitly request to replace/delete the link first." },
    { k_EResultRemoteFileConflict, "The sync cannot resume due to a conflict between the local and remote files." },
    { k_EResultIllegalPassword, "The requested new password is not allowed." },
    { k_EResultSameAsPreviousValue, "New value is the same as the old one. This is used for secret question and answer." },
    { k_EResultAccountLogonDenied, "Account login denied due to 2nd factor authentication failure." },
    { k_EResultCannotUseOldPassword, "The requested new password is not legal." },
    { k_EResultInvalidLoginAuthCode, "Account login denied due to auth code invalid." },
    { k_EResultAccountLogonDeniedNoMail, "Account login denied due to 2nd factor auth failure - and no mail has been sent." },
    { k_EResultHardwareNotCapableOfIPT, "The users hardware does not support Intel's Identity Protection Technology (IPT)." },
    { k_EResultIPTInitError, "Intel's Identity Protection Technology (IPT) has failed to initialize." },
    { k_EResultParentalControlRestricted, "Operation failed due to parental control restrictions for current user." },
    { k_EResultFacebookQueryError, "Facebook query returned an error." },
    { k_EResultExpiredLoginAuthCode, "Account login denied due to an expired auth code." },
    { k_EResultIPLoginRestrictionFailed, "The login failed due to an IP restriction." },
    { k_EResultAccountLockedDown, "The current users account is currently locked for use. This is likely due to a hijacking and pending ownership verification." },
    { k_EResultAccountLogonDeniedVerifiedEmailRequired, "The logon failed because the accounts email is not verified." },
    { k_EResultNoMatchingURL, "There is no URL matching the provided values." },
    { k_EResultBadResponse, "Bad Response due to a Parse failure, missing field, etc." },
    { k_EResultRequirePasswordReEntry, "The user cannot complete the action until they re-enter their password." },
    { k_EResultValueOutOfRange, "The value entered is outside the acceptable range." },
    { k_EResultUnexpectedError, "Something happened that we didn't expect to ever happen." },
    { k_EResultDisabled, "The requested service has been configured to be unavailable." },
    { k_EResultInvalidCEGSubmission, "The files submitted to the CEG server are not valid." },
    { k_EResultRestrictedDevice, "The device being used is not allowed to perform this action." },
    { k_EResultRegionLocked, "The action could not be complete because it is region restricted." },
    { k_EResultRateLimitExceeded, "Temporary rate limit exceeded, try again later, different from k_EResultLimitExceeded which may be permanent." },
    { k_EResultAccountLoginDeniedNeedTwoFactor, "Need two-factor code to login." },
    { k_EResultItemDeleted, "The thing we're trying to access has been deleted." },
    { k_EResultAccountLoginDeniedThrottle, "Login attempt failed, try to throttle response to possible attacker." },
    { k_EResultTwoFactorCodeMismatch, "Two factor authentication (Steam Guard) code is incorrect." },
    { k_EResultTwoFactorActivationCodeMismatch, "The activation code for two-factor authentication (Steam Guard) didn't match." },
    { k_EResultAccountAssociatedToMultiplePartners, "The current account has been associated with multiple partners." },
    { k_EResultNotModified, "The data has not been modified." },
    { k_EResultNoMobileDevice, "The account does not have a mobile device associated with it." },
    { k_EResultTimeNotSynced, "The time presented is out of range or tolerance." },
    { k_EResultSmsCodeFailed, "SMS code failure - no match, none pending, etc." },
    { k_EResultAccountLimitExceeded, "Too many accounts access this resource." },
    { k_EResultAccountActivityLimitExceeded, "Too many changes to this account." },
    { k_EResultPhoneActivityLimitExceeded, "Too many changes to this phone." },
    { k_EResultRefundToWallet, "Cannot refund to payment method, must use wallet." },
    { k_EResultEmailSendFailure, "Cannot send an email." },
    { k_EResultNotSettled, "Can't perform operation until payment has settled." },
    { k_EResultNeedCaptcha, "The user needs to provide a valid captcha." },
    { k_EResultGSLTDenied, "A game server login token owned by this token's owner has been banned." },
    { k_EResultGSOwnerDenied, "Game server owner is denied for some other reason such as account locked, community ban, vac ban, missing phone, etc." },
    { k_EResultInvalidItemType, "The type of thing we were requested to act on is invalid." },
    { k_EResultIPBanned, "The IP address has been banned from taking this action." },
    { k_EResultGSLTExpired, "This Game Server Login Token (GSLT) has expired from disuse; it can be reset for use." },
    { k_EResultInsufficientFunds, "User doesn't have enough wallet funds to complete the action." },
    { k_EResultTooManyPending, "There are too many of this thing pending already." },
    { k_EResultNoSiteLicensesFound, "No site licenses found." },
    { k_EResultWGNetworkSendExceeded, "WG max network send size exceeded." },
    { k_EResultAccountNotFriends, "The accounts are not mutual friends." },
    { k_EResultLimitedUserAccount, "The user account is limited." },
    { k_EResultCantRemoveItem, "Item cannot be removed." },
    { k_EResultAccountDeleted, "The account has been deleted." },
    { k_EResultExistingUserCancelledLicense, "A license already exists, but was cancelled." },
    { k_EResultCommunityCooldown, "Access is denied due to a community cooldown." }, 
    { k_EResultNoLauncherSpecified, "No launcher was specified, but is required to choose correct realm." },
    { k_EResultMustAgreeToSSA, "User must agree to China SSA or global SSA before logging in." },
    { k_EResultLauncherMigrated, "Specified launcher type is no longer supported." },
    { k_EResultSteamRealmMismatch, "The user's realm does not match the realm of the requested resource." },
    { k_EResultInvalidSignature, "Signature check did not match." },
    { k_EResultParseFailure, "Failed to parse input." },
    { k_EResultNoVerifiedPhone, "Account does not have a verified phone number." }
  };

  // clang-format on

}